name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: Z4EQLbW8ime4actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel twine
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Init .pypirc
      env:
        PYPI_USERNAME_TOKEN: ${{ secrets.PYPI_USERNAME_TOKEN}}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        PYPI_TEST_TOKEN: ${{ secrets.PYPI_TEST_TOKEN }}
      run: |
        echo -e '[pypi]' >> ~/.pypirc
        echo -e "username = ${PYPI_USERNAME_TOKEN}" >> ~/.pypirc
        echo -e "password = ${PYPI_TOKEN}" >> ~/.pypirc
        echo -e '' >> ~/.pypirc
        echo -e '[testpypi]' >> ~/.pypirc
        echo -e "repository = https://test.pypi.org/legacy/" >> ~/.pypirc
        echo -e "username = ${PYPI_USERNAME_TOKEN}" >> ~/.pypirc
        echo -e "password = ${PYPI_TEST_TOKEN}" >> ~/.pypirc
    - name: Preparation for publishment
      run: |
        python setup.py sdist
        python setup.py bdist_wheel
    - name: Publish test
      run: |
        twine check dist/*
        twine upload -r testpypi dist/*
    - name: Publish
      run: |
        twine upload dist/*